let STATUS_CODES = {
	SUCCESS : 200,
	SUCCESS_CREATED : 201,
	SESSION_EXPIRED: 399,
	BAD_REQUEST : 400,
	UNAUTHORIZED : 401,
	VISA: 402,
	FORBIDDEN : 403,
	NOT_FOUND : 404,
	NO_VISA_USER_ID : 405,
	SERVER_ERROR : 500
};

let ERROR_MESSAGE = {
	USER_NOT_FOUND: "No such user found. Please Try again!",
	PASSWORD_INCORRECT: "Password is wrong. Please try again!"
}
exports.STATUS_CODES = STATUS_CODES;
exports.ERROR_MESSAGE = ERROR_MESSAGE;